name: South Florida Officiants
favicon: null
layout_spectrum: 0.59699
typography_spectrum: 0.753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b565a7'
    - '#356825'
    - '#351e31'
    - '#77b565'
    - '#800080'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
